---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Collect only facts about hardware
      setup:
        gather_subset:
          - 'hardware'

    - name: Test for available disk space
      setup: filter=ansible_mounts

    # - name: Ensure that free space on the tested volume is greater than 15%
    #   assert:
    #     that:
    #       - mount.size_available > mount.size_total|float * 0.05
    #     msg: Disk space has reached 95% threshold
    #   vars:
    #     mount: "{{ ansible_mounts | selectattr('mount','equalto',item.mount) | list | first }}"
    #   with_items:
    #     - "{{ ansible_mounts }}"

    - debug:
        msg: "ansible_mounts {{ ansible_mounts }}"
      vars:
        mount: "{{ ansible_mounts | selectattr('mount','equalto',item.mount) | list | first }}"

    - name: Checking space
      assert:
        that:
          - item.size_available|int > 104857600
      when: item.mount == "/"
      with_items: "{{ ansible_mounts }}"
      register: disk_free

    - debug:
        msg: "item.size_available / 1000000000 | round(1,'common') {{ item.size_available / 1000000000 | round(1,'common') }}"
      when: item.mount == "/"
      with_items: "{{ ansible_mounts }}"

    - debug:
        msg: "item.size_available {{ item.size_available }}"
      when: item.mount == "/"
      with_items: "{{ ansible_mounts }}"